#!/bin/bash

set -e

# in case of early job failure, make sure output files exist

export PATH=/opt/conda/bin:/opt/miniconda/bin:$PATH

tar xzf Mechanistic_Pan-Cancer_Model.tar.gz

export OMP_NUM_THREADS=8

python3 trail.py

echo
echo
echo "Model done. Current state of the the files:"
ls -lh
echo

# rename the csv files so we can easily untar later
for FILE in `ls *.csv`; do
    mv $FILE $1-$FILE
done

# output now is a tarfile with *.csv
tar czf $1.tar.gz *.csv

