#!/bin/bash

set -e

# in case of early job failure, make sure output files exist

export PATH=/opt/conda/bin:/opt/miniconda/bin:$PATH

tar xzf Mechanistic_Pan-Cancer_Model.tar.gz

export OMP_NUM_THREADS=4

# This will run jobs in the jobs directory in the model dir
python3 test.py

echo
echo
echo "Model done. Current state of the the files:"
ls -lh
echo

# rename the csv files so we can easily untar later
FILES=""
for FILE in `ls *.csv *.pdf 2>/dev/null`; do
    mv $FILE $1-$FILE
    FILES="$FILES $1-$FILE"
done

echo
echo "Taring up this result files:"
echo "$FILES"

# output now is a tarfile with the results
tar czf $1.tar.gz $FILES

