#!/bin/bash

set -e

# in case of early job failure, make sure output files exist
touch $1-xoutS_0.csv
touch $1-xoutG_0.csv
touch $1-t_0.csv

export PATH=/opt/conda/bin:/opt/miniconda/bin:$PATH

tar xzf Mechanistic_Pan-Cancer_Model.tar.gz

export OMP_NUM_THREADS=8

python3 test2.py

mv xoutS_0.csv $1-xoutS_0.csv
mv xoutG_0.csv $1-xoutG_0.csv
mv t_0.csv $1-t_0.csv

