#!/bin/bash

set -e

# in case of early job failure, make sure output files exist

export PATH=/opt/conda/bin:/opt/miniconda/bin:$PATH

tar xzf Mechanistic_Pan-Cancer_Model.tar.gz

export OMP_NUM_THREADS=8

python3 test2.py

echo
echo
echo "Model done. Current state of the the files:"
ls -lh
echo

# rename output files
for FILE in \
    t_deterministic.csv \
    t_stochastic.csv \
    xoutG_deterministic.csv \
    xoutG_stochastic.csv \
    xoutS_deterministic.csv \
    xoutS_stochastic.csv \
; do
    if [ ! -e $FILE ]; then
        echo "ERROR: expected output file $FILE does not exist"
        exit 1
    fi
    mv $FILE $1-$FILE
done

